version: "3.8"

services:
  app:
    container_name: app_container
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8081
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: default
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:  # Remove later
      - "5432:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

  traefik:
    image: traefik:v2.8
    ports:
      - "8008:80"
      - "8081:8080"
    volumes:
      - "./traefik.dev.toml:/etc/traefik/traefik.toml"  # Синхронизируется с внешним "on-fly". Для прода заменить
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: